#!/bin/bash
# pbs launching script example for NAMD job

#     job name:
#PBS -N trainNS 
#PBS -P RDS-FEI-NRMMCI-RW

#     how many cpus?
#PBS -l ncpus=4

#PBS -l pmem=4000mb

# How long to run the job? (hours:minutes:seconds)
#PBS -l walltime=0:4:0

#     Name of output file:
#PBS -o train-output.txt

#     Environmental varibles to make it work:
 
module load matlab 
cd $PBS_O_WORKDIR
 
#     Launching the job!

matlab -nodesktop -nodisplay -nosplash -r "run('train.m')"
